### ISSUE TITLE
Modified Apache 2.0 License is detected as default Apache

### ISSUE THREAD

**Issue by ShaneCurcuru** [benbalter/licensee#192]
See https://github.com/wg/wrk/blob/master/LICENSE

Github displays this as the default "Apache License 2.0" even though the title of the license clearly says "Modified", and there are additional terms within the license text.  This can result in users being surprised later on if the author attempts to exert their rights from the additional clause, because with how Github makes their "_project_ is licensed under the _X_ license", many users may not see the change in the license text.

Thanks for considering!

**Comment by mlinksva** [comment]
There's one term added:

> {+(e) If the Derivative Work includes substantial changes to features+}
> {+          or functionality of the Work, then you must remove the name of+}
> {+          the Work, and any derivation thereof, from all copies that you+}
> {+          distribute, whether in Source or Object form, except as required+}
> {+          in copyright, patent, trademark, and attribution notices.+}

Current version of licensee does obtain a false positive:

> $ script/git-repo https://github.com/wg/wrk
> License file: LICENSE
> License hash: bd7a4313aa73d2af6278b3fc4a0ae083b490a003
> License: Apache License 2.0
> Confidence: 98.44%
> Method: Licensee::Matchers::Dice

A few possible fixes that would be relatively easy:

1. Check for required string present in Apache-2.0 (eg "Version 2.0, January 2004"), similar proposed at https://github.com/benbalter/licensee/issues/191#issuecomment-302187397 but not yet implemented
2. Make similarity (% of words in common) increase with wordcount (currently 95%, making it easier for longer licenses to get false positive matches like this one); getting right factor would require fiddling
3. Different attack on false positives for long licenses without changing % words in common: reject match if absolute number of words is different; again getting this right would require fiddling

(Longer term it might be interesting to implement a different matcher leveraging the SPDX markup of license texts, which indicates parts that are optional or templated.)

**Comment by clr-apache** [comment]
I'd prefer 100% match of the license, not 95% or 98%. Just eliminate false positives completely.

Either it is the Apache License, Version 2.0 or it is not. 

The suggestion for people to apply the Apache License 2.0 to their own work is to refer to the license in the header of each source file, *not* to change the license.
http://www.apache.org/licenses/LICENSE-2.0.html#apply

**Comment by mlinksva** [comment]
I'd also prefer to eliminate false positives completely by requiring a 100% match (at least for non-templated licenses). I've not tried this yet as it would require substantial test changes, at the least. In the meantime, I've suggested a simple and stupid fix for this and other instance of modified long license false positives in #198.

**Comment by clr-apache** [comment]
The project https://github.com/wg/wrk still is advertised as being licensed under Apache 2.0 license, which it is not.

How does #198 fix this issue for this project?

**Comment by benbalter** [comment]
This is fixed on `master` for https://github.com/wg/wrk, and should be eventually updated on GitHub:

```
➜  licensee git:(master) script/git-repo https://github.com/wg/wrk
License file: LICENSE
License hash: bd7a4313aa73d2af6278b3fc4a0ae083b490a003
License: Not detected
```

**Comment by clr-apache** [comment]
Thanks for the update. I'd prefer to keep this one open until it's visible. I'll keep an eye on it.

**Comment by clr-apache** [comment]
It has now been 28 days and the project still shows as being licensed under Apache 2.0.
https://github.com/wg/wrk/blob/master/LICENSE and https://github.com/wg/wrk both show this.

It is not.

What are the plans to update this incorrect information?

**Comment by benbalter** [comment]
Reopening in light of https://github.com/benbalter/licensee/pull/205#issue-238585162.

**Comment by mlinksva** [comment]
This issue is still fixed. FCPL false positive for MPL-2.0 is another issue, opened #207 for that.

**Comment by clr-apache** [comment]
It has now been 40 days and the project still shows as being licensed under Apache 2.0.
https://github.com/wg/wrk/blob/master/LICENSE and https://github.com/wg/wrk both show this.

**Comment by benbalter** [comment]
@clr-apache this is the bug tracker for an open source project. If you have a question about a feature on GItHub.com, please [contact GitHub support](https://github.com/contact).

**Comment by clr-apache** [comment]
@benbalter sorry about that. my issue is with github not your tool.
